# Commands to start on workspace startup
tasks:
   - before: source ~/.cargo/env 
     init: cargo build --release
# Ports to expose on workspace startup
ports:
   - port: 9944
#     onOpen: open-preview

image:
  file: .gitpod.Dockerfile
